version: "2"
services:
  mongo:
    image: mongo:latest
    expose:
    - "27017"
  nacos:
    image: paderlol/nacos:latest
    container_name: nacos-standalone
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - TZ=Asia/Shanghai
    ports:
      - "8848:8848"
    volumes:
      - ./logs:/home/nacos/logs
  elasticsearch:
    image: elasticsearch:5.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    command: elasticsearch
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      TZ: "Asia/Shanghai"
#  logstash:
#    image: logstash:5.1.1
#    ports:
#      - "12201:12201/udp"
#    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
#      output { elasticsearch { hosts => ["elasticsearch"] } }'
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
#    environment:
#      - TZ=Asia/Shanghai
  kibana:
    image: kibana:5.1.1
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - TZ=Asia/Shanghai
    links:
      - elasticsearch
      - graylog2
    depends_on:
      - graylog2
  # Graylog: https://hub.docker.com/r/graylog/graylog/
  graylog2:
    image: graylog/graylog:2.4.0-1
    environment:
      #CHANGE ME!
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://192.168.61.137:9000/api
      - TZ=Asia/Shanghai
    links:
      - elasticsearch
      - mongo
    depends_on:
      - elasticsearch
      - mongo
    ports:
      - 9000:9000
      - 514:514
      - 514:514/udp
      - 12201:12201
      - 12201:12201/udp
    command: -e 'input { gelf { host => "0.0.0.0" port => 12201 } }
          output { elasticsearch { hosts => ["elasticsearch"] } }'
  spring-nacos-server:
    image: spring-cloud-docker/spring-nacos-server
    depends_on:
      - nacos
      - graylog2
    links:
      - nacos
      - graylog2
    ports:
      - "8001:8001"
    environment:
      - TZ=Asia/Shanghai
  spring-nacos-client:
    image: spring-cloud-docker/spring-nacos-client
    depends_on:
      - nacos
      - graylog2
    environment:
      - TZ=Asia/Shanghai
    links:
      - nacos
      - graylog2
    ports:
      - "8002:8002"
    extra_hosts:
      - "dockernet:${EXTERNAL_IP}"
